server:
  port: 8080
spring:
  application:
    name: flash-sale
  datasource:
    url: jdbc:mysql://localhost:3306/flash-sale
    username: root
    password: 4582872
  redis:
    host: 192.168.5.128
    port: 6379
    database: 0
    password:
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数
        max-idle: 8 # 连接池最大空闲连接数
        min-idle: 0 # 连接池最小空闲连接数
        max-wait: -1ms # 连接池最大阻塞等待时间，负值表示没有限制
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  rabbitmq:
    host: localhost # rabbitmq的连接地址
    port: 5672 # rabbitmq的连接端口号
    virtual-host: /flashSale # rabbitmq的虚拟host
    username: flashSale # rabbitmq的用户名
    password: flashSale # rabbitmq的密码



#mybatis-plus:
#  mapper-locations:
#    - classpath:mapper/*.xml
#    - classpath*:com/**/mapper/*.xml
# 自定义redis key
#redis:
#  key:
#    prefix:
#      authCode: "portal:authCode:"
#    expire:
#      authCode: 120 # 验证码超期时间
## 自定义jwt key
#jwt:
#  tokenHeader: Authorization #JWT存储的请求头
#  secret: mySecret #JWT加解密使用的密钥
#  expiration: 604800 #JWT的超期限时间(60*60*24)
#  tokenHead: Bearer  #JWT负载中拿到开头
#
#
#secure:
#  ignored:
#    urls: #安全路径白名单
#      - /swagger-ui/
#      - /swagger-resources/**
#      - /**/v2/api-docs
#      - /**/*.html
#      - /**/*.js
#      - /**/*.css
#      - /**/*.png
#      - /favicon.ico
#      - /actuator/**
#      - /druid/**

#      - /admin/**